### ISSUE TITLE
create funtion to opt out of registration fee

### ISSUE THREAD

**Issue by chicklegirl** [jamestunnell/homeschool-co-op#10]
Good afternoon, James! I hope you all had a peaceful Christmas.

We're going to be offering a study hall session during this coming term for the co-op, and wanted to be able to opt out of the registration fee (which is currently automatically added to the cost), so that families could enroll and then pay a donation on a drop-in basis.

Thanks,
Katie

**Comment by jamestunnell** [comment]
Katie,

Each section now has a separate registration fee, which defaults to 10. So for existing sections you can edit this and make it 0, and for new sections you can choose 0 before it is created. The change is already live so you can try it out.

**Comment by chicklegirl** [comment]
Thank you, James. It works perfectly!
