### ISSUE TITLE
Classes have no enrollement limit

### ISSUE THREAD

**Issue by jamestunnell** [jamestunnell/homeschool-co-op#7]
By adding an (optional?) enrollment limit, a class can be set up to show both the number enrolled and the number of available seats.

**Comment by jamestunnell** [comment]
Okay, class sections have (optional) enrollment limits now. If the enrollment limit is set, then if the limit has been met and someone tries to enroll then it will fail and inform them that the limit has been met.

Additionally, this feature could be expanded to incorporate wait lists for classes that are full. That's a bit more work, though.

**Comment by jamestunnell** [comment]
Added in 63ac125

**Comment by chicklegirl** [comment]
Thanks! It's working great.
