### ISSUE TITLE
Create/link a new contact email for co-op

### ISSUE THREAD

**Issue by chicklegirl** [jamestunnell/homeschool-co-op#9]
Heather Briggs-Hunholz said that there's no longer an email account set up for when people try to contact the co-op. I'd be willing to set up a new email account on Gmail, but Heather said we needed to work with you to get that linked through the website.

**Comment by jamestunnell** [comment]
Yeah, if you want a different email address just let me know and I can update the contact form. Best to keep that email address private, so why don't you send it to me via email or Facebook?
